arbitrum = 42161
arbitrum_goerli = 421613
arbitrum_testnet = 79377087078960
avalanche = 43114
avalanche_testnet = 43113
bsc = 56
bsc_testnet = 97
celo = 42220
fantom = 250
fantom_testnet = 4002
fuse = 122
goerli = 5
harmony = 1666600000
harmony_testnet = 1666700000
heco = 128
heco_testnet = 256
kovan = 42
mainnet = 1
matic = 137
matic_testnet = 80001
moonbeam_testnet = 1287
moonriver = 1285
okex = 66
okex_testnet = 65
palm = 11297108109
palm_testnet = 11297108099
rinkeby = 4
ropsten = 3
xdai = 100
